### PR TITLE
Multisite caching

### PR DESCRIPTION
**Pull request by lige-development**
Tiny patch to enable multisite full page caching

### CODE REVIEW

**Comment by luklewluk** [comment]
@lige-development Thank you very much for the PR! Is it fixing https://github.com/luklewluk/SupercachePlugin/issues/12 too?

**Comment by luklewluk** [comment]
@lige-development could you allow me to push to your fork? - https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

I would like to improve a few things and add new nginx configuration before merge.

**Comment by lige-development** [comment]
@luklewluk actually I didn't knew about #12 ... so, technically not. The reason for #12 is in .htaccess setting, which I solved commenting out the 

`#RewriteRule ^plugins/.*$ / [F,L]`

(actually you could put it beneath the supercache setting)

**Comment by lige-development** [comment]
@luklewluk sure :)

**Pull request merged**
